BROWSERSYNC:
  # URL of local development server goes here (ex. http://localsite.dev)
  url: "localhost:6250/"
  
# Set to true if you want static asset revisioning, helpful for cache busting
REVISIONING: false

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 9"
  - "ios >= 7"
# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "public/dist"

  # Path to Angular JS controllers
  controllers: 
   - "public/controllers/**"
   - "!public/controllers/AppController.js"

  # Paths to static assets that aren't images, CSS, or JavaScript
  assets:
    - "src/assets/**/*"
    - "!src/assets/{images,images/**/*,scss,scss/**/*}"
  # Paths to Sass libraries, which can then be loaded with @import
  sass:
    - "node_modules/foundation-sites/scss"
    - "node_modules/motion-ui/src"
  # Paths to JavaScript entry points for webpack to bundle modules
  entries:
    - "**/src/assets/js/app.js"
    - "!**/*.js"

  package:
    - "**/public/**"
    - "!**/api/**"
    - "!**/node_modules/**"
    - "!**/packaged/**"
    - "!**/src/**"
    - "!**/app.js"
    - "!**/config.yml"
    - "!**/.env"
    - "!**/gulpfile.babel.js"
    - "!**/package.json"
    - "!**/package-lock.json"